# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created: Tue Jul 01 14:27:07 2014
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.individualTab = QtGui.QWidget()
        self.individualTab.setObjectName(_fromUtf8("individualTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.individualTab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.individualTab)
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Base class:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.indivBaseClass_comboBox = QtGui.QComboBox(self.individualTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.indivBaseClass_comboBox.sizePolicy().hasHeightForWidth())
        self.indivBaseClass_comboBox.setSizePolicy(sizePolicy)
        self.indivBaseClass_comboBox.setObjectName(_fromUtf8("indivBaseClass_comboBox"))
        self.indivBaseClass_comboBox.addItem(_fromUtf8(""))
        self.indivBaseClass_comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "PYGA_Individual", None, QtGui.QApplication.UnicodeUTF8))
        self.indivBaseClass_comboBox.addItem(_fromUtf8(""))
        self.indivBaseClass_comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "PYGA_StandardMultiObjIndividual", None, QtGui.QApplication.UnicodeUTF8))
        self.indivBaseClass_comboBox.addItem(_fromUtf8(""))
        self.indivBaseClass_comboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "PYGA_StandardMultiObjIndividual_NSGAII", None, QtGui.QApplication.UnicodeUTF8))
        self.indivBaseClass_comboBox.addItem(_fromUtf8(""))
        self.indivBaseClass_comboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "PYGA_StandardVectorMultiObjIndividual_NSGAII", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout.addWidget(self.indivBaseClass_comboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.multiObj_checkBox = QtGui.QCheckBox(self.individualTab)
        self.multiObj_checkBox.setText(QtGui.QApplication.translate("MainWindow", "Multi objective", None, QtGui.QApplication.UnicodeUTF8))
        self.multiObj_checkBox.setObjectName(_fromUtf8("multiObj_checkBox"))
        self.verticalLayout_2.addWidget(self.multiObj_checkBox)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.indiv_treeWidget = QtGui.QTreeWidget(self.individualTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.indiv_treeWidget.sizePolicy().hasHeightForWidth())
        self.indiv_treeWidget.setSizePolicy(sizePolicy)
        self.indiv_treeWidget.setHeaderHidden(True)
        self.indiv_treeWidget.setObjectName(_fromUtf8("indiv_treeWidget"))
        item_0 = QtGui.QTreeWidgetItem(self.indiv_treeWidget)
        self.indiv_treeWidget.topLevelItem(0).setText(0, QtGui.QApplication.translate("MainWindow", "Attributs", None, QtGui.QApplication.UnicodeUTF8))
        item_0 = QtGui.QTreeWidgetItem(self.indiv_treeWidget)
        self.indiv_treeWidget.topLevelItem(1).setText(0, QtGui.QApplication.translate("MainWindow", "Overloaded methods", None, QtGui.QApplication.UnicodeUTF8))
        item_0 = QtGui.QTreeWidgetItem(self.indiv_treeWidget)
        self.indiv_treeWidget.topLevelItem(2).setText(0, QtGui.QApplication.translate("MainWindow", "Specific methods", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout_3.addWidget(self.indiv_treeWidget)
        self.indiv_groupBox = QtGui.QGroupBox(self.individualTab)
        self.indiv_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "GroupBox", None, QtGui.QApplication.UnicodeUTF8))
        self.indiv_groupBox.setObjectName(_fromUtf8("indiv_groupBox"))
        self.verticalLayout_indiv = QtGui.QVBoxLayout(self.indiv_groupBox)
        self.verticalLayout_indiv.setObjectName(_fromUtf8("verticalLayout_indiv"))
        self.horizontalLayout_3.addWidget(self.indiv_groupBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.individualTab, _fromUtf8(""))
        self.behaviorTab = QtGui.QWidget()
        self.behaviorTab.setObjectName(_fromUtf8("behaviorTab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.behaviorTab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.behaviorTab)
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Base class:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.behavBaseClass_comboBox = QtGui.QComboBox(self.behaviorTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.behavBaseClass_comboBox.sizePolicy().hasHeightForWidth())
        self.behavBaseClass_comboBox.setSizePolicy(sizePolicy)
        self.behavBaseClass_comboBox.setObjectName(_fromUtf8("behavBaseClass_comboBox"))
        self.behavBaseClass_comboBox.addItem(_fromUtf8(""))
        self.behavBaseClass_comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "PYGA_GenAlgBehavior", None, QtGui.QApplication.UnicodeUTF8))
        self.behavBaseClass_comboBox.addItem(_fromUtf8(""))
        self.behavBaseClass_comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "PYGA_StandardGenAlgBehavior", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout_2.addWidget(self.behavBaseClass_comboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.behav_treeWidget = QtGui.QTreeWidget(self.behaviorTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.behav_treeWidget.sizePolicy().hasHeightForWidth())
        self.behav_treeWidget.setSizePolicy(sizePolicy)
        self.behav_treeWidget.setHeaderHidden(True)
        self.behav_treeWidget.setObjectName(_fromUtf8("behav_treeWidget"))
        item_0 = QtGui.QTreeWidgetItem(self.behav_treeWidget)
        self.behav_treeWidget.topLevelItem(0).setText(0, QtGui.QApplication.translate("MainWindow", "Overloaded methods", None, QtGui.QApplication.UnicodeUTF8))
        item_0 = QtGui.QTreeWidgetItem(self.behav_treeWidget)
        self.behav_treeWidget.topLevelItem(1).setText(0, QtGui.QApplication.translate("MainWindow", "Specific methods", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout_4.addWidget(self.behav_treeWidget)
        self.behav_groupBox = QtGui.QGroupBox(self.behaviorTab)
        self.behav_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "GroupBox", None, QtGui.QApplication.UnicodeUTF8))
        self.behav_groupBox.setObjectName(_fromUtf8("behav_groupBox"))
        self.verticalLayout_behav = QtGui.QVBoxLayout(self.behav_groupBox)
        self.verticalLayout_behav.setObjectName(_fromUtf8("verticalLayout_behav"))
        self.horizontalLayout_4.addWidget(self.behav_groupBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.behaviorTab, _fromUtf8(""))
        self.runParamTab = QtGui.QWidget()
        self.runParamTab.setObjectName(_fromUtf8("runParamTab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.runParamTab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.param_treeWidget = QtGui.QTreeWidget(self.runParamTab)
        self.param_treeWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.param_treeWidget.setAutoExpandDelay(-1)
        self.param_treeWidget.setObjectName(_fromUtf8("param_treeWidget"))
        self.param_treeWidget.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Parameter", None, QtGui.QApplication.UnicodeUTF8))
        self.param_treeWidget.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_4.addWidget(self.param_treeWidget)
        self.tabWidget.addTab(self.runParamTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.run_pushButton = QtGui.QPushButton(self.centralwidget)
        self.run_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.run_pushButton.setObjectName(_fromUtf8("run_pushButton"))
        self.horizontalLayout_5.addWidget(self.run_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        __sortingEnabled = self.indiv_treeWidget.isSortingEnabled()
        self.indiv_treeWidget.setSortingEnabled(False)
        self.indiv_treeWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.individualTab), QtGui.QApplication.translate("MainWindow", "Individual", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.behav_treeWidget.isSortingEnabled()
        self.behav_treeWidget.setSortingEnabled(False)
        self.behav_treeWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.behaviorTab), QtGui.QApplication.translate("MainWindow", "Behavior", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.runParamTab), QtGui.QApplication.translate("MainWindow", "Run parameters", None, QtGui.QApplication.UnicodeUTF8))

